
-- Profiles table to store user bio-stats
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY DEFAULT auth.uid(),
  name TEXT NOT NULL,
  age INTEGER,
  weight FLOAT,
  height_feet INTEGER,
  height_inches INTEGER,
  gender TEXT,
  goal TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Daily logs table with JSONB for flexible food/exercise entry storage
CREATE TABLE IF NOT EXISTS daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  food JSONB DEFAULT '[]'::jsonb,
  exercise JSONB DEFAULT '[]'::jsonb,
  hydration INTEGER DEFAULT 0,
  sleep_hours FLOAT DEFAULT 0,
  sedentary_hours FLOAT DEFAULT 0,
  UNIQUE(profile_id, date)
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_logs ENABLE ROW LEVEL SECURITY;

-- Note: In this specific demo context using GUEST_ID, we use public access.
-- In a real app, replace `true` with `auth.uid() = profile_id`.
CREATE POLICY "Allow all for guest" ON profiles FOR ALL USING (true);
CREATE POLICY "Allow all for guest logs" ON daily_logs FOR ALL USING (true);
